### ISSUE TITLE
When can we expect 9.0.5.0 build?

### ISSUE THREAD

**Issue by stephet3** [WASdev/ci.docker.ibm-http-server#39]
I am beginning to wonder if this is going to keep up with the rapid changes?

**Comment by naumanna** [comment]
Ah, let me get it out there.  Our focus lately has been on the supported images for WebSphere Traditional and Liberty so I missed IHS.  I'll update this issue when it is available.

**Comment by naumanna** [comment]
The 9.0.5.0 image is now available in Docker Hub - https://hub.docker.com/r/ibmcom/ibm-http-server/
