### ISSUE TITLE
ibm-http-server image not available

### ISSUE THREAD

**Issue by KirkFitzDev** [WASdev/ci.docker.ibm-http-server#45]
Hi,

Has  ibmcom/ibm-http-server been removed
https://hub.docker.com/r/ibmcom/ibm-http-server/
It was there 2 days ago... now its gone

Regards,

Kirk

**Comment by covener** [comment]
Yes.  Sorry for the inconvenience on this. We discovered early this year that the images were unmaintained for an extended period of time (18+ months) and was almost completely silent on the support front for just as long. The decision was to remove.  
They can be built from this repo from the IIM downloads (these projects pre-date the IHS archive distribution which is another alternative for some use of these images)

 Can you share a little about how your usage?  If you'd rather not share it publicly you can email me or even open a case in the IBM support portal and tag it with my name.
(anyone else reading is welcome as well to append/email/support or just 👍  the top post).

**Comment by arungpro** [comment]
Hi @covener Even i was interested in ibmcom/ibm-http-server as I wanted to run a simple IHS endpoint on my local and maybe start my learning from there.

**Comment by covener** [comment]
@arungpro simplified Instructions for creating a similar image are available here: https://github.com/WASdev/ci.docker.ibm-http-server/tree/master/archive

Depending on the details of what you're learning, you may find it more convenient to use non-IHS Apache images from Dockerhub https://hub.docker.com/_/httpd or as provided as part of any linux distributions image.
